security:
    firewalls:
      dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
      anonymous:
            anonymous: ~

    providers:
        in_memory:
            memory: